name: Sonar

on:
  push:
    branches: [ "main" ]

jobs:
  sonar-scan:
    runs-on: [self-hosted,linux,commerce-1]
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.19.0

      - name: Build & test (JaCoCo)
        run: mvn -B clean verify

      - name: SonarQube Scan (backend)
        run: |
          mvn -B sonar:sonar \
          -Dsonar.projectKey=Commerce \
          -Dsonar.projectName=Commerce \
          -Dsonar.coverage.exclusions=** \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
          -Dsonar.qualitygate.wait=true